################################################################################
#
#
#
################################################################################

all:
	$(CD) framework && $(MAKE) && echo "_________    BUILD LIBRARY DONE    _________"

clean:
	$(CD) framework && $(MAKE) clean && echo "_________    LIBRARY CLEAR    _________"

install:
	$(CD) framework && $(MAKE) install && echo "_________    LIBRARY INSTALLED    _________"

